In [ ]:
import numpy as np# Importamos la librería numpy y le asignamos el alias 'np' por convención
vector = np.array ([1,2,3,4,5]) # Creamos un vector (arreglo de 1 dimensión) con 5 elementos
matriz = np.array ([[1,2,3],[4,5,6]]) # Creamos una matriz (arreglo de 2 dimensiones) de 2 filas y 3 columnas
print(vector.ndim, vector.shape) # Imprimimos el número de dimensiones (ndim) y la forma (shape) del vector
print(matriz.ndim, matriz.shape)# Imprimimos el número de dimensiones y la forma de la matriz

1 (5,)
2 (2, 3)


In [ ]:
A = np.array([[1,2], [3,4]]) # Creamos dos matrices de 2x2
B= np.array([[5,6], [7,8]])

C=A+B# Sumamos las matrices A y B elemento por elemento
D= np.sqrt(A) # Calculamos la raíz cuadrada (sqrt) de cada elemento de la matriz A
# Imprimimos las matrices originales
print(A)
print(B)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [ ]:
imagen = np.random.randint(0, 255, (5, 5)) # Generamos una matriz de 5x5 con números enteros aleatorios entre 0 y 254
#region central
roi = imagen[1:4, 1:4]

imagen_norm = imagen / 255.0# Normalizamos los valores de la imagen para que estén en el rango de 0.0 a 1.0


# Imprimimos la región extraída y la matriz con los valores normalizados
print(roi)
print(imagen_norm)

[[116  46 197]
 [ 70  49 147]
 [ 75 251 190]]
[[0.74509804 0.54509804 0.09803922 0.2745098  0.42352941]
 [0.62745098 0.45490196 0.18039216 0.77254902 0.52941176]
 [0.13333333 0.2745098  0.19215686 0.57647059 0.05882353]
 [0.87058824 0.29411765 0.98431373 0.74509804 0.99215686]
 [0.74901961 0.7254902  0.68235294 0.72941176 0.96470588]]
